# Generated by Django 5.1.2 on 2025-04-14 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_scan_input',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('asset', models.CharField(max_length=255, verbose_name='资产')),
                ('asset_type', models.CharField(choices=[('URL', 'URL'), ('Domain', 'Domain'), ('IP', 'IP'), ('小程序', '小程序'), ('APP', 'APP')], max_length=10, verbose_name='资产类型')),
                ('asset_add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='资产创建时间')),
                ('asset_editor_time', models.DateTimeField(auto_now=True, null=True, verbose_name='资产最新修改时间')),
                ('asset_note', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '扫描资产详情',
            },
        ),
        migrations.CreateModel(
            name='Ehole_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ehole_result', models.CharField(blank=True, max_length=1024, null=True, verbose_name='网站标题')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('editor_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最新修改时间')),
            ],
            options={
                'verbose_name_plural': 'url资产详情',
            },
        ),
        migrations.CreateModel(
            name='GroupPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.JSONField(blank=True, null=True, verbose_name='菜单路径')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_path', to='auth.group')),
            ],
            options={
                'verbose_name': '权限组路径',
                'verbose_name_plural': '权限组路径',
            },
        ),
        migrations.CreateModel(
            name='OneforallResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP地址')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='标题')),
                ('addr', models.CharField(blank=True, max_length=1024, null=True, verbose_name='地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('editor_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最新修改时间')),
            ],
            options={
                'verbose_name_plural': 'OneForall扫描结果',
            },
        ),
        migrations.CreateModel(
            name='Poc_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poc_name', models.CharField(max_length=128, unique=True, verbose_name='POC名称')),
                ('content', models.CharField(blank=True, max_length=128000, null=True, verbose_name='POC内容')),
                ('author', models.CharField(blank=True, max_length=128, null=True, verbose_name='作者')),
                ('severity', models.CharField(blank=True, choices=[('低危', '低危'), ('中危', '中危'), ('高危', '高危')], max_length=128, null=True, verbose_name='威胁等级')),
                ('cvss_score', models.FloatField(blank=True, null=True, verbose_name='CVSS评分')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('product', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('editor_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最新修改时间')),
            ],
            options={
                'verbose_name_plural': 'POC管理',
            },
        ),
        migrations.CreateModel(
            name='Poctags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='标签名字')),
            ],
            options={
                'verbose_name_plural': 'POC标签',
            },
        ),
        migrations.CreateModel(
            name='Tide_result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('finger', models.TextField(blank=True, max_length=1024, null=True, verbose_name='指纹信息')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('editor_time', models.DateTimeField(auto_now=True, null=True, verbose_name='最新修改时间')),
            ],
            options={
                'verbose_name_plural': 'Tide输出',
            },
        ),
        migrations.CreateModel(
            name='Wih_result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=1024, null=True, verbose_name='类型')),
                ('content', models.TextField(max_length=1024, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': 'wih扫描结果',
            },
        ),
        migrations.DeleteModel(
            name='Poc',
        ),
        migrations.AlterModelOptions(
            name='asset_info',
            options={'verbose_name_plural': '输入资产详情'},
        ),
        migrations.RenameField(
            model_name='sensitive_dir',
            old_name='info',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='sensitive_info',
            name='info',
        ),
        migrations.AddField(
            model_name='ip_info',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='服务信息'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目用户'),
        ),
        migrations.AddField(
            model_name='scan_info',
            name='Dirsearch_scan_if',
            field=models.BooleanField(default=True, verbose_name='Dirsearch调用'),
        ),
        migrations.AddField(
            model_name='scan_info',
            name='JSFinder_scan_if',
            field=models.BooleanField(default=True, verbose_name='JSFinder调用'),
        ),
        migrations.AddField(
            model_name='scan_info',
            name='Oneforall_scan_if',
            field=models.BooleanField(default=True, verbose_name='Oneforall调用'),
        ),
        migrations.AddField(
            model_name='scan_info',
            name='Wih_scan_if',
            field=models.BooleanField(default=True, verbose_name='wih调用'),
        ),
        migrations.AddField(
            model_name='sensitive_dir',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='状态码'),
        ),
        migrations.AddField(
            model_name='sensitive_dir',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='sensitive_info',
            name='js_info',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='敏感js文件'),
        ),
        migrations.AddField(
            model_name='sensitive_info',
            name='other',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='敏感api接口'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_group', to='auth.group', verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='domain_info',
            name='subdomain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='子域名'),
        ),
        migrations.AlterField(
            model_name='ip_info',
            name='service',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='端口服务'),
        ),
        migrations.AddField(
            model_name='asset_scan_input',
            name='asset_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects', verbose_name='所属单位'),
        ),
        migrations.AddField(
            model_name='ehole_info',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.asset_info', verbose_name='扫描目标'),
        ),
        migrations.AddField(
            model_name='oneforallresult',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset_info', verbose_name='扫描目标'),
        ),
        migrations.AddField(
            model_name='poc_info',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.poctags', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='tide_result',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset_info', verbose_name='扫描目标'),
        ),
        migrations.AddField(
            model_name='wih_result',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asset_info', verbose_name='扫描目标'),
        ),
        migrations.DeleteModel(
            name='Url_info',
        ),
    ]
