# Generated by Django 3.2.13 on 2024-11-07 05:27
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='domain_info',
            name='subdomain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='子域名'),
        ),
    ]